import { db } from "@workspace/db";
import { companiesTable, jobsTable, articlesTable } from "@workspace/db/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(articlesTable);
  await db.delete(jobsTable);
  await db.delete(companiesTable);

  const companies = await db
    .insert(companiesTable)
    .values([
      {
        name: "Nubank",
        slug: "nubank",
        logo: "https://logo.clearbit.com/nubank.com.br",
        coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop",
        tagline: "Lutamos contra a complexidade para devolver o controle da vida financeira às pessoas.",
        description: "O Nubank é uma das maiores fintechs do mundo, fundada em 2013 com a missão de combater a complexidade e o abuso do sistema financeiro tradicional. Com mais de 90 milhões de clientes, o Nubank redefine a relação das pessoas com o dinheiro através de produtos simples, transparentes e eficientes. Nossa cultura é orientada por dados e obsessão pelo cliente, com times autônomos e uma mentalidade de startup em escala.",
        category: "fintech",
        size: "grande",
        foundedYear: 2013,
        employeeCount: 8000,
        averageAge: 29,
        genderRatio: "48% mulheres",
        videoUrl: "https://www.youtube.com/embed/kfMF36QYLXY",
        city: "São Paulo",
        state: "SP",
        website: "https://nubank.com.br",
        featured: true,
        benefits: ["Plano de saúde premium", "Stock options", "Home office flexível", "Gympass", "Day off no aniversário", "Licença maternidade/paternidade estendida", "Auxílio creche", "Snacks e refeições"],
        values: ["Simplicidade", "Autonomia", "Foco no cliente", "Diversidade e inclusão", "Transparência"],
        photos: [
          "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "iFood",
        slug: "ifood",
        logo: "https://logo.clearbit.com/ifood.com.br",
        coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=400&fit=crop",
        tagline: "Conectando pessoas a comida de qualidade de forma simples e rápida.",
        description: "O iFood é o maior aplicativo de delivery de comida da América Latina. Com presença em mais de 1.000 cidades, conectamos milhões de pessoas a restaurantes e entregadores todos os dias. Nossa missão é deixar as pessoas mais livres para viver melhor. Somos uma empresa orientada por dados, com cultura de inovação e experimentação constante.",
        category: "tech",
        size: "grande",
        foundedYear: 2011,
        employeeCount: 5000,
        averageAge: 31,
        genderRatio: "44% mulheres",
        city: "Osasco",
        state: "SP",
        website: "https://ifood.com.br",
        featured: true,
        benefits: ["Plano de saúde", "Vale-refeição", "Home office híbrido", "Gympass", "Bônus por desempenho", "Parcerias com restaurantes", "Curso de idiomas"],
        values: ["Inovação", "Simplicidade", "Impacto", "Colaboração", "Ousadia"],
        photos: [
          "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Conta Simples",
        slug: "conta-simples",
        logo: "https://logo.clearbit.com/contasimples.com",
        coverImage: "https://images.unsplash.com/photo-1462206092226-f46025ffe607?w=1200&h=400&fit=crop",
        tagline: "A conta empresarial feita para quem não tem tempo a perder.",
        description: "A Conta Simples é uma fintech B2B que oferece conta empresarial, cartão de crédito e gestão de despesas para startups e PMEs. Fundada em 2018, nossa missão é simplificar a vida financeira dos empreendedores brasileiros. Somos uma startup em rápido crescimento, com cultura muito próxima ao cliente e foco em produto.",
        category: "fintech",
        size: "startup",
        foundedYear: 2018,
        employeeCount: 180,
        averageAge: 27,
        genderRatio: "40% mulheres",
        city: "São Paulo",
        state: "SP",
        website: "https://contasimples.com",
        featured: true,
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Home office budget", "Cursos e livros", "Day off no aniversário"],
        values: ["Foco no cliente", "Ownership", "Transparência", "Aprendizado contínuo"],
        photos: [
          "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "RD Station",
        slug: "rd-station",
        logo: "https://logo.clearbit.com/rdstation.com",
        coverImage: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=1200&h=400&fit=crop",
        tagline: "Ajudamos empresas a crescer com marketing digital e CRM.",
        description: "A RD Station é a maior plataforma de marketing digital e CRM da América Latina. Fundada em Florianópolis em 2011, hoje atendemos mais de 50.000 empresas no Brasil e no mundo. Nossa cultura é baseada em autonomia, aprendizado e impacto real nos negócios dos nossos clientes. Aqui você vai crescer profissionalmente em um ambiente desafiador e colaborativo.",
        category: "marketing",
        size: "grande",
        foundedYear: 2011,
        employeeCount: 1200,
        averageAge: 30,
        genderRatio: "52% mulheres",
        city: "Florianópolis",
        state: "SC",
        website: "https://rdstation.com",
        featured: true,
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Bônus anual", "Cursos pagos", "Participação nos lucros", "Auxílio internet"],
        values: ["Aprendizado", "Resultado", "Diversidade", "Autonomia", "Felicidade"],
        photos: [
          "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=500&fit=crop",
        ],
        teamVideos: [
          { url: "https://www.youtube.com/embed/8S0FDjFBj8o", name: "Mariana Ferreira", role: "Engenheira de Software Pleno" },
          { url: "https://www.youtube.com/embed/iCvmsMzlF7o", name: "Diego Moraes", role: "Growth Manager" },
          { url: "https://www.youtube.com/embed/6JYIGclVQdw", name: "Camila Andrade", role: "Customer Success Manager" },
        ],
      },
      {
        name: "Loft",
        slug: "loft",
        logo: "https://logo.clearbit.com/loft.com.br",
        coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=400&fit=crop",
        tagline: "Reinventando o mercado imobiliário com tecnologia.",
        description: "A Loft é uma proptech que usa tecnologia para simplificar a compra e venda de imóveis residenciais no Brasil. Fundada em 2018 e com aporte de mais de U$700 milhões, somos uma das startups mais valiosas do país. Nosso time combina talentos de tecnologia, produto e negócios para transformar o setor imobiliário.",
        category: "tech",
        size: "media",
        foundedYear: 2018,
        employeeCount: 800,
        averageAge: 30,
        city: "São Paulo",
        state: "SP",
        website: "https://loft.com.br",
        featured: false,
        benefits: ["Plano de saúde", "Stock options", "Home office flexível", "Gympass", "Bônus por metas"],
        values: ["Inovação", "Integridade", "Colaboração", "Impacto"],
        photos: [
          "https://images.unsplash.com/photo-1497366858526-0766cadbe8fa?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Hotmart",
        slug: "hotmart",
        logo: "https://logo.clearbit.com/hotmart.com",
        coverImage: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=1200&h=400&fit=crop",
        tagline: "A plataforma para quem cria, vende e distribui produtos digitais.",
        description: "A Hotmart é a maior plataforma de produtos digitais da América Latina. Conectamos criadores de conteúdo a milhões de compradores em mais de 190 países. Fundada em BH em 2011, hoje somos um unicórnio e seguimos crescendo com a missão de democratizar o empreendedorismo digital. Nossa cultura celebra a liberdade, a criatividade e o crescimento individual — acreditamos que pessoas felizes criam produtos incríveis.",
        category: "tech",
        size: "grande",
        foundedYear: 2011,
        employeeCount: 1800,
        averageAge: 28,
        genderRatio: "55% mulheres",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        city: "Belo Horizonte",
        state: "MG",
        website: "https://hotmart.com",
        featured: true,
        benefits: ["Plano de saúde premium", "Stock options", "Home office total", "Cursos ilimitados", "Day off no aniversário", "Gympass", "Auxílio internet", "Licença parental estendida"],
        values: ["Liberdade", "Crescimento", "Impacto", "Diversidade", "Inovação"],
        photos: [
          "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Pipefy",
        slug: "pipefy",
        logo: "https://logo.clearbit.com/pipefy.com",
        coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=400&fit=crop",
        tagline: "Automatize processos e ganhe eficiência com nossa plataforma no-code.",
        description: "O Pipefy é uma plataforma de gestão de processos e automação sem código. Atendemos empresas em mais de 150 países e estamos mudando a forma como as organizações trabalham. Nossa cultura é international-first, com times distribuídos pelo Brasil e pelo mundo, e forte compromisso com a excelência no produto.",
        category: "tech",
        size: "media",
        foundedYear: 2015,
        employeeCount: 600,
        averageAge: 29,
        genderRatio: "38% mulheres",
        city: "Curitiba",
        state: "PR",
        website: "https://pipefy.com",
        featured: false,
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Inglês custeado", "Home office budget", "Gympass"],
        values: ["Excelência", "Ownership", "Aprendizado", "Colaboração"],
        photos: [
          "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Sympla",
        slug: "sympla",
        logo: "https://logo.clearbit.com/sympla.com.br",
        coverImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&h=400&fit=crop",
        tagline: "A plataforma de eventos mais usada do Brasil.",
        description: "A Sympla é a maior plataforma de venda de ingressos e gestão de eventos do Brasil. Atendemos mais de 200.000 eventos por ano, desde shows a cursos online. Somos parte do grupo Locaweb e seguimos crescendo como startup dentro de um grupo de tecnologia consolidado.",
        category: "tech",
        size: "media",
        foundedYear: 2012,
        employeeCount: 350,
        averageAge: 30,
        city: "Belo Horizonte",
        state: "MG",
        website: "https://sympla.com.br",
        featured: false,
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Cursos pagos", "Participação nos lucros"],
        values: ["Inovação", "Simplicidade", "Foco no cliente", "Agilidade"],
        photos: [
          "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
        ],
      },
      // ── Santa Catarina ──────────────────────────────────────────────
      {
        name: "WEG",
        slug: "weg",
        logo: "https://logo.clearbit.com/weg.net",
        coverImage: "https://images.unsplash.com/photo-1581093806997-124204d9fa9d?w=1200&h=400&fit=crop",
        tagline: "Tecnologia que move o mundo — de Jaraguá do Sul para o planeta.",
        description: "A WEG é uma das maiores fabricantes de equipamentos elétricos do mundo, fundada em 1961 em Jaraguá do Sul/SC. Com presença em mais de 135 países e mais de 40.000 colaboradores, investimos fortemente em tecnologia, automação e digitalização industrial. Nossa área de TI e Digital está crescendo aceleradamente — buscamos engenheiros, analistas e especialistas em dados para transformar a indústria global com software e inteligência artificial.",
        category: "industria",
        size: "grande",
        foundedYear: 1961,
        employeeCount: 40000,
        averageAge: 33,
        genderRatio: "32% mulheres",
        city: "Jaraguá do Sul",
        state: "SC",
        website: "https://weg.net",
        featured: true,
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Restaurante no local", "Gympass", "Previdência privada", "Programa de desenvolvimento profissional"],
        values: ["Inovação", "Qualidade", "Integridade", "Comprometimento", "Sustentabilidade"],
        photos: [
          "https://images.unsplash.com/photo-1581093806997-124204d9fa9d?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1560472355-a3b4d4da8e90?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=500&fit=crop",
        ],
        teamVideos: [
          { url: "https://www.youtube.com/embed/8S0FDjFBj8o", name: "Ana Rodrigues", role: "Engenheira de Software — Automação" },
          { url: "https://www.youtube.com/embed/6JYIGclVQdw", name: "Carlos Medeiros", role: "Diretor de Inovação Digital" },
          { url: "https://www.youtube.com/embed/UF8uR6Z6KLc", name: "Fernanda Bauer", role: "Analista de Dados Industriais" },
        ],
      },
      {
        name: "Havan",
        slug: "havan",
        logo: "https://logo.clearbit.com/havan.com.br",
        coverImage: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1200&h=400&fit=crop",
        tagline: "O maior varejo de Santa Catarina está se transformando em tech.",
        description: "A Havan é uma das maiores redes de varejo do Brasil, com mais de 180 lojas e sede em Brusque/SC. Estamos em acelerada transformação digital, investindo fortemente em e-commerce, dados, automação e novas tecnologias. Nossa área de tecnologia cresce a cada ano — buscamos talentos que queiram construir o varejo do futuro junto com a gente, com a solidez de uma empresa que fatura mais de R$ 10 bilhões por ano.",
        category: "varejo",
        size: "grande",
        foundedYear: 1986,
        employeeCount: 18000,
        averageAge: 31,
        genderRatio: "55% mulheres",
        city: "Brusque",
        state: "SC",
        website: "https://havan.com.br",
        featured: true,
        benefits: ["Plano de saúde", "Vale-refeição", "Desconto em compras Havan", "Participação nos lucros", "Auxílio transporte", "Gympass"],
        values: ["Cliente em primeiro lugar", "Ética", "Trabalho em equipe", "Inovação", "Resultado"],
        photos: [
          "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Softplan",
        slug: "softplan",
        logo: "https://logo.clearbit.com/softplan.com.br",
        coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop",
        tagline: "Software que transforma a gestão pública e da construção no Brasil.",
        description: "A Softplan é uma das maiores empresas de software do Brasil, com foco em soluções para o Judiciário, Ministério Público, e setor de construção civil. Fundada em 1990 em Florianópolis, somos referência em tecnologia para gestão pública e privada. Com mais de 2.000 colaboradores, nossa cultura valoriza inovação, qualidade técnica e impacto real na sociedade brasileira. Venha construir software que processa processos judiciais de milhões de brasileiros.",
        category: "govtech",
        size: "grande",
        foundedYear: 1990,
        employeeCount: 2200,
        averageAge: 32,
        genderRatio: "41% mulheres",
        city: "Florianópolis",
        state: "SC",
        website: "https://softplan.com.br",
        featured: true,
        benefits: ["Plano de saúde", "Home office híbrido", "Participação nos lucros", "Auxílio educação", "Gympass", "Bônus por desempenho", "Auxílio internet"],
        values: ["Inovação", "Qualidade", "Colaboração", "Crescimento", "Impacto social"],
        photos: [
          "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=500&fit=crop",
        ],
        teamVideos: [
          { url: "https://www.youtube.com/embed/iCvmsMzlF7o", name: "Pedro Oliveira", role: "Engenheiro de Software Sênior" },
          { url: "https://www.youtube.com/embed/8S0FDjFBj8o", name: "Juliana Santos", role: "Product Manager — GovTech" },
          { url: "https://www.youtube.com/embed/6JYIGclVQdw", name: "Roberto Leal", role: "Tech Lead — Judiciário" },
        ],
      },
      {
        name: "Portobello",
        slug: "portobello",
        logo: "https://logo.clearbit.com/portobello.com.br",
        coverImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=400&fit=crop",
        tagline: "Design, tecnologia e sustentabilidade moldando o futuro.",
        description: "A Portobello é uma das maiores fabricantes de revestimentos cerâmicos do mundo, fundada em 1977 em Tijucas/SC. Com mais de 4.000 colaboradores e presença em 70 países, investimos pesado em digitalização, automação de fábrica e e-commerce. Nossa área de tecnologia lidera projetos de IoT industrial, data analytics e transformação digital. Aqui, a indústria encontra a inovação.",
        category: "industria",
        size: "grande",
        foundedYear: 1977,
        employeeCount: 4200,
        averageAge: 34,
        genderRatio: "38% mulheres",
        city: "Tijucas",
        state: "SC",
        website: "https://portobello.com.br",
        featured: false,
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Restaurante no local", "Transporte fretado", "Previdência privada"],
        values: ["Inovação", "Sustentabilidade", "Qualidade", "Pessoas", "Performance"],
        photos: [
          "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1586864387789-628af9feed72?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=500&fit=crop",
        ],
        teamVideos: [
          { url: "https://www.youtube.com/embed/UF8uR6Z6KLc", name: "Camila Luz", role: "Desenvolvedora Frontend" },
          { url: "https://www.youtube.com/embed/iCvmsMzlF7o", name: "Lucas Pereira", role: "Analista de BI" },
          { url: "https://www.youtube.com/embed/8S0FDjFBj8o", name: "Renata Nunes", role: "Eng. de Dados IoT" },
        ],
      },
    ])
    .returning();

  console.log(`Inserted ${companies.length} companies`);

  const jobs = await db
    .insert(jobsTable)
    .values([
      {
        title: "Senior Software Engineer - Backend",
        slug: "senior-software-engineer-backend-nubank",
        companyId: companies[0].id,
        category: "tech",
        description: "Buscamos um(a) engenheiro(a) de software sênior para trabalhar com nosso time de plataforma, desenvolvendo sistemas distribuídos de alta escala que processam milhões de transações diárias. Você vai trabalhar com Clojure, Kotlin, AWS e Kafka em um ambiente de alta performance e autonomia.",
        requirements: ["5+ anos de experiência com desenvolvimento backend", "Experiência com sistemas distribuídos", "Conhecimento em Clojure ou Kotlin (diferencial)", "Experiência com AWS", "Inglês intermediário"],
        benefits: ["Plano de saúde premium", "Stock options", "Home office flexível", "Gympass"],
        faq: [
          { question: "É obrigatório anexar currículo?", answer: "Sim, é necessário anexar seu currículo para se candidatar a esta vaga." },
          { question: "Esta vaga oferece trabalho remoto?", answer: "A vaga é em regime híbrido — você trabalhará alguns dias no escritório em São Paulo e outros remotamente." },
          { question: "Qual o tipo de contrato oferecido?", answer: "O contrato é CLT com todos os benefícios da legislação trabalhista brasileira." },
          { question: "Inglês é obrigatório?", answer: "Inglês intermediário é exigido para comunicação com times e documentação técnica. Inglês avançado é um diferencial." },
        ],
        city: "São Paulo",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 18000,
        salaryMax: 28000,
        featured: true,
      },
      {
        title: "Product Manager - Growth",
        slug: "product-manager-growth-nubank",
        companyId: companies[0].id,
        category: "produto",
        description: "Como PM de Growth no Nubank, você será responsável por identificar e explorar oportunidades para aumentar a aquisição, ativação e retenção de clientes. Trabalhará de forma cross-funcional com engenharia, design e data science para lançar features que impactem milhões de usuários.",
        requirements: ["4+ anos de experiência em product management", "Experiência com growth hacking e métricas de produto", "Capacidade analítica forte", "Experiência com testes A/B", "Inglês fluente"],
        benefits: ["Plano de saúde premium", "Stock options", "Home office flexível"],
        city: "São Paulo",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 20000,
        salaryMax: 30000,
        featured: true,
      },
      {
        title: "Data Analyst - Marketing",
        slug: "data-analyst-marketing-ifood",
        companyId: companies[1].id,
        category: "dados",
        description: "Você vai trabalhar no time de analytics de marketing do iFood, ajudando a entender o comportamento dos usuários e otimizar campanhas. Usamos SQL, Python e ferramentas de BI para gerar insights que impactam diretamente a estratégia da empresa.",
        requirements: ["2+ anos de experiência em análise de dados", "SQL avançado", "Experiência com Python (pandas, numpy)", "Conhecimento em ferramentas de BI (Tableau, Looker)", "Raciocínio analítico"],
        benefits: ["Plano de saúde", "Vale-refeição", "Home office híbrido", "Gympass"],
        city: "Osasco",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 8000,
        salaryMax: 13000,
        featured: false,
      },
      {
        title: "UX Designer - Mobile",
        slug: "ux-designer-mobile-ifood",
        companyId: companies[1].id,
        category: "design",
        description: "Buscamos um(a) UX Designer para trabalhar no aplicativo de consumidores do iFood. Você vai fazer pesquisa com usuários, criar wireframes e protótipos, e colaborar de perto com engenharia e produto para criar experiências excepcionais para nossos 50 milhões de usuários.",
        requirements: ["3+ anos de experiência em UX design", "Portfólio com projetos de mobile", "Experiência com Figma", "Conhecimento em design research", "Capacidade de comunicação clara"],
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Cursos pagos"],
        city: "Osasco",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 9000,
        salaryMax: 14000,
        featured: false,
      },
      {
        title: "Full Stack Engineer",
        slug: "full-stack-engineer-conta-simples",
        companyId: companies[2].id,
        category: "tech",
        description: "Na Conta Simples você vai trabalhar como engenheiro(a) full stack construindo a infraestrutura financeira para PMEs brasileiras. Nossa stack é React, Node.js e PostgreSQL. Somos um time pequeno e autônomo, onde cada pessoa tem grande impacto.",
        requirements: ["2+ anos de experiência full stack", "React e TypeScript", "Node.js", "PostgreSQL", "Experiência com APIs REST"],
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Home office budget"],
        city: "São Paulo",
        state: "SP",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 10000,
        salaryMax: 16000,
        featured: true,
      },
      {
        title: "Marketing Manager - Inbound",
        slug: "marketing-manager-inbound-rdstation",
        companyId: companies[3].id,
        category: "marketing",
        description: "A RD Station busca um(a) Marketing Manager para liderar a estratégia de inbound marketing. Você vai gerenciar a produção de conteúdo, SEO e estratégias de geração de leads para nosso ICP de PMEs. Experiência com a própria plataforma RD Station é um grande diferencial.",
        requirements: ["4+ anos de experiência em marketing digital", "Experiência com inbound marketing e SEO", "Capacidade analítica para interpretar métricas", "Experiência com CRM", "Liderança de times"],
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Bônus anual"],
        city: "Florianópolis",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 11000,
        salaryMax: 17000,
        featured: false,
      },
      {
        title: "Estágio em Produto Digital",
        slug: "estagio-produto-digital-hotmart",
        companyId: companies[5].id,
        category: "produto",
        description: "Junte-se ao time de produto da Hotmart como estagiário(a) e aprenda na prática como construir produtos digitais usados por milhões de pessoas. Você vai trabalhar junto com PMs e designers em pesquisas, análises e discovery de produto.",
        requirements: ["Cursando últimos semestres de curso superior em Administração, Engenharia ou áreas relacionadas", "Interesse em tecnologia e produtos digitais", "Boa comunicação", "Inglês intermediário"],
        benefits: ["Bolsa auxílio compatível", "Plano de saúde", "Cursos ilimitados", "Day off no aniversário"],
        faq: [
          { question: "É obrigatório anexar currículo?", answer: "Sim, é necessário anexar currículo e carta de apresentação para se candidatar." },
          { question: "Esta vaga aceita trabalho remoto?", answer: "A vaga é híbrida. Você trabalhará alguns dias presencialmente em Belo Horizonte." },
          { question: "Qual o tipo de contrato?", answer: "Estágio supervisionado com contrato formal, bolsa auxílio e benefícios." },
          { question: "Há possibilidade de efetivação?", answer: "Sim! A Hotmart tem histórico de efetivação de estagiários com alto desempenho ao fim do estágio." },
        ],
        city: "Belo Horizonte",
        state: "MG",
        modality: "hibrido",
        contractType: "estagio",
        level: "junior",
        salaryMin: 2000,
        salaryMax: 3000,
        featured: false,
      },
      {
        title: "Frontend Engineer - React",
        slug: "frontend-engineer-react-pipefy",
        companyId: companies[6].id,
        category: "tech",
        description: "Buscamos um(a) Frontend Engineer para trabalhar na interface do Pipefy, usada por empresas ao redor do mundo. Nossa stack é React, TypeScript e GraphQL. Você vai construir features complexas de uma plataforma no-code de gestão de processos.",
        requirements: ["3+ anos de experiência com React", "TypeScript", "GraphQL", "Testes automatizados", "Inglês para comunicação com time internacional"],
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Inglês custeado", "Home office budget"],
        city: "Curitiba",
        state: "PR",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 10000,
        salaryMax: 16000,
        featured: false,
      },
      {
        title: "Tech Lead - Plataforma",
        slug: "tech-lead-plataforma-nubank",
        companyId: companies[0].id,
        category: "tech",
        description: "Estamos buscando um(a) Tech Lead para o time de plataforma do Nubank. Você vai liderar tecnicamente um time de engenheiros, definir a arquitetura de sistemas de alta escala e garantir a qualidade do código e das entregas. Experiência com liderança técnica e sistemas distribuídos é essencial.",
        requirements: ["7+ anos de experiência em engenharia de software", "Experiência com liderança técnica de times", "Sistemas distribuídos e cloud", "Clojure, Kotlin ou linguagens funcionais (diferencial)", "Inglês fluente"],
        benefits: ["Plano de saúde premium", "Stock options agressivos", "Bônus por performance", "Home office flexível"],
        faq: [
          { question: "É obrigatório anexar currículo?", answer: "Sim, currículo atualizado é obrigatório. Portfólio técnico ou GitHub são bem-vindos." },
          { question: "Esta vaga permite trabalho remoto?", answer: "A vaga é híbrida com flexibilidade. Presença no escritório de São Paulo pode ser necessária em alguns momentos." },
          { question: "O processo seletivo é em inglês?", answer: "Parte do processo pode ser conduzida em inglês. Fluência é um requisito para esta posição." },
          { question: "Qual o tipo de contrato?", answer: "CLT com pacote de remuneração competitivo, incluindo stock options e bônus por performance." },
        ],
        city: "São Paulo",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "especialista",
        salaryMin: 28000,
        salaryMax: 42000,
        featured: true,
      },
      {
        title: "Social Media Analyst",
        slug: "social-media-analyst-hotmart",
        companyId: companies[5].id,
        category: "marketing",
        description: "A Hotmart busca um(a) Social Media Analyst criativo(a) para gerenciar nossa presença nas redes sociais no Brasil e América Latina. Você vai criar conteúdo, gerir campanhas e analisar métricas de engajamento para uma marca que inspira empreendedores.",
        requirements: ["2+ anos de experiência em social media", "Criatividade e produção de conteúdo", "Conhecimento em métricas de redes sociais", "Experiência com ferramentas de gestão (Sprout, Buffer)", "Espanhol é diferencial"],
        benefits: ["Plano de saúde premium", "Stock options", "Home office total", "Cursos ilimitados"],
        faq: [
          { question: "É obrigatório anexar currículo?", answer: "Sim. Portfólio de redes sociais gerenciadas anteriormente é um diferencial importante." },
          { question: "Esta vaga é 100% remota?", answer: "Sim! A Hotmart adota o modelo de trabalho 100% remoto para esta posição." },
          { question: "Qual o tipo de contrato?", answer: "CLT com todos os benefícios, incluindo stock options e cursos ilimitados na plataforma Hotmart." },
          { question: "O espanhol é obrigatório?", answer: "Não é obrigatório, mas é um grande diferencial para atuar com as operações da América Latina." },
        ],
        city: "Belo Horizonte",
        state: "MG",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 5000,
        salaryMax: 8000,
        featured: false,
      },
      // ── WEG vagas ───────────────────────────────────────────────────
      {
        title: "Desenvolvedor(a) de Software Sênior - Automação Industrial",
        slug: "dev-software-senior-automacao-weg",
        companyId: companies[8].id,
        category: "tech",
        description: "Na WEG você vai construir soluções de software embarcado e sistemas de controle para equipamentos elétricos e automação industrial usados em mais de 135 países. Trabalharemos com C++, Python e arquiteturas de sistemas embarcados de alta confiabilidade. Um desafio técnico único, com escala global.",
        requirements: ["5+ anos de experiência em desenvolvimento de software", "Experiência com C++ ou Python para sistemas industriais", "Conhecimento em protocolos industriais (Modbus, OPC-UA, PROFIBUS)", "Experiência com sistemas embarcados (diferencial)", "Inglês intermediário"],
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Restaurante no local", "Gympass", "Previdência privada"],
        faq: [
          { question: "Preciso ter experiência com automação industrial?", answer: "Experiência com automação industrial é um diferencial, mas não obrigatório. Valorizamos sólida base em engenharia de software e disposição para aprender o domínio." },
          { question: "A vaga é presencial em Jaraguá do Sul?", answer: "Sim, a vaga é presencial na nossa sede em Jaraguá do Sul/SC. Oferecemos auxílio para relocação a candidatos de outras cidades." },
          { question: "Há possibilidade de trabalho internacional?", answer: "Sim! Com presença em mais de 135 países, há oportunidades de projetos e viagens internacionais." },
          { question: "Qual o tipo de contrato?", answer: "CLT com pacote completo de benefícios, incluindo participação nos lucros e previdência privada." },
        ],
        city: "Jaraguá do Sul",
        state: "SC",
        modality: "presencial",
        contractType: "clt",
        level: "senior",
        salaryMin: 12000,
        salaryMax: 20000,
        featured: true,
      },
      {
        title: "Engenheiro(a) de Dados - Analytics",
        slug: "engenheiro-dados-analytics-weg",
        companyId: companies[8].id,
        category: "dados",
        description: "A WEG está construindo sua plataforma de dados global. Você vai trabalhar com ingestão, transformação e disponibilização de dados industriais e de negócio em larga escala. Nossa stack inclui Spark, Databricks, Azure e dbt. Um desafio de dados de proporções globais.",
        requirements: ["3+ anos de experiência em engenharia de dados", "Experiência com Spark ou Databricks", "SQL avançado", "Python para pipelines de dados", "Experiência com plataformas cloud (Azure preferencial)"],
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Restaurante no local", "Previdência privada"],
        city: "Jaraguá do Sul",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 10000,
        salaryMax: 16000,
        featured: false,
      },
      {
        title: "Analista de Infraestrutura Cloud",
        slug: "analista-infra-cloud-weg",
        companyId: companies[8].id,
        category: "tech",
        description: "Faça parte do time de Cloud da WEG e ajude a migrar e operar a infraestrutura global de uma das maiores indústrias do mundo. Trabalharemos com Azure, Kubernetes, Terraform e práticas de DevSecOps para garantir alta disponibilidade dos sistemas industriais.",
        requirements: ["2+ anos de experiência com cloud (Azure, AWS ou GCP)", "Kubernetes e containers Docker", "Terraform ou Ansible para IaC", "Experiência com CI/CD", "Inglês básico para documentação"],
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Gympass", "Previdência privada"],
        city: "Jaraguá do Sul",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 9000,
        salaryMax: 14000,
        featured: false,
      },
      // ── Havan vagas ─────────────────────────────────────────────────
      {
        title: "Desenvolvedor(a) Backend - E-commerce",
        slug: "dev-backend-ecommerce-havan",
        companyId: companies[9].id,
        category: "tech",
        description: "A Havan está acelerando sua transformação digital e precisa de engenheiros backend para construir a plataforma de e-commerce do futuro. Você vai trabalhar com Java/Spring Boot e arquitetura de microsserviços para suportar o crescimento explosivo das vendas online de uma das maiores redes varejistas do Brasil.",
        requirements: ["3+ anos de experiência com desenvolvimento backend", "Java com Spring Boot ou Node.js", "Arquitetura de microsserviços", "PostgreSQL ou MySQL", "Experiência com mensageria (Kafka, RabbitMQ)"],
        benefits: ["Plano de saúde", "Vale-refeição", "Desconto em compras Havan", "Participação nos lucros", "Gympass"],
        faq: [
          { question: "A vaga é presencial em Brusque?", answer: "A vaga é híbrida, com alguns dias na sede em Brusque/SC e possibilidade de home office em outros dias." },
          { question: "Preciso ter experiência com e-commerce?", answer: "Experiência com e-commerce é valorizada, mas o mais importante é sólida experiência com desenvolvimento backend e APIs." },
          { question: "Qual o tipo de contrato?", answer: "CLT com todos os benefícios, incluindo desconto em compras em todas as lojas Havan do Brasil." },
          { question: "Há processo de integração estruturado?", answer: "Sim, temos um programa de onboarding de 30 dias com mentoria e imersão na cultura e sistemas da empresa." },
        ],
        city: "Brusque",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 8000,
        salaryMax: 13000,
        featured: true,
      },
      {
        title: "Analista de Dados - Varejo e Inteligência Comercial",
        slug: "analista-dados-varejo-havan",
        companyId: companies[9].id,
        category: "dados",
        description: "Junte-se ao time de dados da Havan e analise o comportamento de milhões de consumidores em mais de 180 lojas físicas e no e-commerce. Você vai gerar insights para precificação, mix de produtos e campanhas promocionais usando SQL, Python e ferramentas de BI.",
        requirements: ["2+ anos de experiência em análise de dados", "SQL avançado", "Python ou R para análise", "Ferramentas de BI (Power BI preferencial)", "Experiência com dados de varejo (diferencial)"],
        benefits: ["Plano de saúde", "Vale-refeição", "Desconto em compras Havan", "Participação nos lucros"],
        city: "Brusque",
        state: "SC",
        modality: "presencial",
        contractType: "clt",
        level: "pleno",
        salaryMin: 6000,
        salaryMax: 10000,
        featured: false,
      },
      // ── Softplan vagas ───────────────────────────────────────────────
      {
        title: "Engenheiro(a) de Software Sênior - Judiciário",
        slug: "engenheiro-software-senior-judiciario-softplan",
        companyId: companies[10].id,
        category: "tech",
        description: "Na Softplan você vai trabalhar no desenvolvimento do SAJ — o maior sistema de gestão judicial do Brasil, usado por mais de 80% dos tribunais do país. Você vai arquitetar soluções em Java e React que processam milhões de processos judiciais, impactando diretamente o acesso à Justiça para todos os brasileiros.",
        requirements: ["5+ anos de experiência em desenvolvimento de software", "Java com Spring Boot", "React ou Angular", "Arquitetura de software e design patterns", "Experiência com sistemas de alta disponibilidade"],
        benefits: ["Plano de saúde", "Home office híbrido", "Participação nos lucros", "Auxílio educação", "Gympass", "Bônus por desempenho"],
        faq: [
          { question: "Preciso ter experiência com sistemas jurídicos?", answer: "Não é necessário. Valorizamos experiência técnica sólida. O domínio jurídico você aprende aqui com nossos especialistas." },
          { question: "A vaga é híbrida?", answer: "Sim, trabalhamos em modelo híbrido com alguns dias de presença no escritório em Florianópolis e home office nos demais dias." },
          { question: "O sistema SAJ realmente é usado em todos os tribunais?", answer: "O SAJ é usado em mais de 80% dos tribunais estaduais do Brasil, além de TRFs, Ministérios Públicos e Defensorias. O impacto é imenso." },
          { question: "Qual o tipo de contrato?", answer: "CLT com pacote competitivo, incluindo PLR e auxílio educação para certificações e cursos." },
        ],
        city: "Florianópolis",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 13000,
        salaryMax: 22000,
        featured: true,
      },
      {
        title: "Product Manager - GovTech",
        slug: "product-manager-govtech-softplan",
        companyId: companies[10].id,
        category: "produto",
        description: "Como PM na Softplan, você vai gerenciar o roadmap de produtos de gestão pública usados por tribunais, ministérios públicos e prefeituras. Você vai entrevistar usuários do setor público, priorizar funcionalidades com impacto real na Justiça e colaborar com times de engenharia e design para lançar melhorias que afetam a vida de milhões de brasileiros.",
        requirements: ["4+ anos de experiência como Product Manager", "Experiência com produtos B2B ou enterprise", "Capacidade analítica para métricas de produto", "Habilidade para se comunicar com stakeholders técnicos e não-técnicos", "Experiência com metodologias ágeis"],
        benefits: ["Plano de saúde", "Home office híbrido", "Participação nos lucros", "Auxílio educação", "Gympass"],
        city: "Florianópolis",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 14000,
        salaryMax: 22000,
        featured: false,
      },
      {
        title: "UX Designer - Plataformas Governamentais",
        slug: "ux-designer-gov-softplan",
        companyId: companies[10].id,
        category: "design",
        description: "Projete interfaces que tornam o Judiciário mais acessível para juízes, promotores, advogados e cidadãos. Na Softplan, o UX tem impacto real na Justiça brasileira. Você vai conduzir pesquisas com usuários do setor público, criar protótipos e validar soluções para sistemas complexos de gestão judicial.",
        requirements: ["3+ anos de experiência em UX Design", "Portfólio com sistemas complexos ou B2B", "Experiência com Figma", "Pesquisa com usuários (entrevistas, testes de usabilidade)", "Capacidade de comunicação com times técnicos"],
        benefits: ["Plano de saúde", "Home office híbrido", "Participação nos lucros", "Auxílio educação"],
        city: "Florianópolis",
        state: "SC",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 8000,
        salaryMax: 13000,
        featured: false,
      },
      // ── Portobello vagas ─────────────────────────────────────────────
      {
        title: "Desenvolvedor(a) Frontend - E-commerce e Showroom Digital",
        slug: "dev-frontend-ecommerce-portobello",
        companyId: companies[11].id,
        category: "tech",
        description: "A Portobello está construindo a experiência digital de uma das marcas de revestimentos mais reconhecidas do mundo. Você vai trabalhar com React, Next.js e ferramentas de visualização 3D para criar showrooms digitais e uma plataforma de e-commerce que conecta arquitetos e consumidores aos produtos Portobello em 70 países.",
        requirements: ["3+ anos de experiência com React", "Next.js ou experiência com SSR/SSG", "TypeScript", "Experiência com e-commerce ou visualização 3D é um diferencial", "Interesse em design e arquitetura"],
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Restaurante no local", "Transporte fretado"],
        faq: [
          { question: "A vaga aceita candidatos de fora de Tijucas?", answer: "Sim! Temos transporte fretado de Florianópolis, Biguaçu, São José e Itajaí. Também há auxílio para relocação." },
          { question: "Qual o modelo de trabalho?", answer: "Híbrido — alguns dias presenciais na fábrica em Tijucas e possibilidade de home office em outros dias." },
          { question: "Vou trabalhar com tecnologias modernas?", answer: "Sim, nossa stack é React + Next.js + TypeScript, com integrações a ferramentas de visualização 3D e plataformas de e-commerce globais." },
          { question: "Qual o tipo de contrato?", answer: "CLT com pacote de benefícios, incluindo PLR e restaurante na fábrica." },
        ],
        city: "Tijucas",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 7000,
        salaryMax: 12000,
        featured: false,
      },
      {
        title: "Analista de Business Intelligence",
        slug: "analista-bi-portobello",
        companyId: companies[11].id,
        category: "dados",
        description: "Analise dados de vendas, produção e logística de uma das maiores fabricantes de revestimentos do mundo. Você vai construir dashboards e relatórios estratégicos para a liderança, usando Power BI, SQL e dados de operações fabris, e-commerce e distribuição em 70 países.",
        requirements: ["2+ anos de experiência com Business Intelligence", "Power BI avançado", "SQL avançado", "Experiência com dados industriais ou de varejo (diferencial)", "Inglês básico para relatórios internacionais"],
        benefits: ["Plano de saúde", "Participação nos lucros", "Auxílio educação", "Restaurante no local", "Transporte fretado"],
        city: "Tijucas",
        state: "SC",
        modality: "presencial",
        contractType: "clt",
        level: "pleno",
        salaryMin: 6000,
        salaryMax: 10000,
        featured: false,
      },
      // ── RD Station + vagas remotas SC ────────────────────────────────
      {
        title: "Engenheiro(a) de Software Pleno - Plataforma",
        slug: "engenheiro-software-pleno-plataforma-rdstation",
        companyId: companies[3].id,
        category: "tech",
        description: "A RD Station busca um(a) engenheiro(a) de software para trabalhar no core da plataforma de CRM e marketing digital mais usada na América Latina. Você vai trabalhar com Ruby on Rails, React e PostgreSQL em um time ágil, com foco em qualidade de código e experiência do usuário.",
        requirements: ["3+ anos de experiência em desenvolvimento web", "Ruby on Rails ou Node.js", "React ou Vue.js", "PostgreSQL", "Testes automatizados (RSpec, Jest)"],
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Bônus anual", "Cursos pagos", "Auxílio internet"],
        city: "Florianópolis",
        state: "SC",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 10000,
        salaryMax: 16000,
        featured: true,
      },
      {
        title: "Customer Success Manager - Mercado PME",
        slug: "customer-success-manager-pme-rdstation",
        companyId: companies[3].id,
        category: "vendas",
        description: "Ajude pequenas e médias empresas a crescerem com a plataforma RD Station. Você vai ser o ponto de contato estratégico de uma carteira de clientes PME, garantindo adoção da plataforma, sucesso nas campanhas de marketing e renovação de contrato. Um papel de altíssimo impacto em uma empresa que já ajudou mais de 50.000 empresas.",
        requirements: ["3+ anos de experiência em customer success ou account management", "Experiência com SaaS", "Conhecimento em marketing digital", "Excelente comunicação e relacionamento", "Capacidade de analisar métricas de sucesso"],
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Bônus anual", "Cursos pagos"],
        city: "Florianópolis",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 7000,
        salaryMax: 11000,
        featured: false,
      },
    ])
    .returning();

  console.log(`Inserted ${jobs.length} jobs`);

  const articles = await db
    .insert(articlesTable)
    .values([
      {
        title: "Como se destacar em processos seletivos de startups em 2024",
        slug: "como-se-destacar-processos-seletivos-startups",
        excerpt: "Startups contratam diferente. Entenda o que os recrutadores de tech realmente buscam e como preparar sua candidatura para se diferenciar.",
        content: "O mercado de trabalho em startups tem características próprias. Diferente de grandes corporações, as startups buscam pessoas com alta autonomia, capacidade de aprender rápido e tolerância à ambiguidade...",
        coverImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=450&fit=crop",
        category: "Carreira",
        author: "Ana Paula Mendes",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
        readTime: 7,
      },
      {
        title: "Salários em tech no Brasil: o que esperar em 2024",
        slug: "salarios-tech-brasil-2024",
        excerpt: "Pesquisa exclusiva com mais de 2.000 profissionais de tecnologia revela as faixas salariais por cargo, nível e stack. Veja como você se posiciona.",
        content: "O mercado de tecnologia no Brasil segue aquecido, mesmo com os movimentos de layoffs globais de 2023. Analisamos dados de mais de 2.000 profissionais para trazer um panorama real das remunerações...",
        coverImage: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=450&fit=crop",
        category: "Mercado",
        author: "Carlos Eduardo Silva",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
        readTime: 10,
      },
      {
        title: "Remote work no Brasil: o guia completo para trabalhar de qualquer lugar",
        slug: "remote-work-brasil-guia-completo",
        excerpt: "Do regime CLT ao PJ, dos impostos à produtividade: tudo que você precisa saber para trabalhar remotamente no Brasil com segurança jurídica e financeira.",
        content: "Trabalho remoto virou realidade para milhões de brasileiros. Mas além da flexibilidade, existem questões práticas importantes: qual regime contratar? Como organizar sua rotina? Como pagar impostos corretamente?...",
        coverImage: "https://images.unsplash.com/photo-1585974738771-84483dd9f89f?w=800&h=450&fit=crop",
        category: "Carreira",
        author: "Mariana Costa",
        authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop",
        readTime: 12,
      },
      {
        title: "Employer branding: por que as melhores startups disputam talentos com cultura",
        slug: "employer-branding-startups-cultura",
        excerpt: "Nubank, iFood, Hotmart. O que essas empresas têm em comum além do tamanho? Uma cultura de empresa que atrai e retém os melhores profissionais. Veja como elas fazem isso.",
        content: "O employer branding virou peça central da estratégia de talentos das startups brasileiras. Com o mercado de tech aquecido e candidatos com múltiplas ofertas, ganham as empresas que constroem marcas empregadoras autênticas...",
        coverImage: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=450&fit=crop",
        category: "Empresas",
        author: "Rafael Gonçalves",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
        readTime: 8,
      },
      {
        title: "CLT ou PJ? O guia definitivo para fazer a escolha certa",
        slug: "clt-ou-pj-guia-definitivo",
        excerpt: "A grande dúvida de quem recebe uma proposta PJ. Calculamos os números reais, incluindo impostos, benefícios e segurança jurídica, para você tomar a melhor decisão.",
        content: "A escolha entre CLT e PJ vai muito além do salário bruto. Envolve impostos, benefícios, segurança jurídica e seu perfil de risco. Neste guia completo, destrinchamos cada variável para você decidir com clareza...",
        coverImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop",
        category: "Carreira",
        author: "Juliana Ferreira",
        authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
        readTime: 15,
      },
      {
        title: "As 10 empresas tech mais desejadas para trabalhar no Brasil em 2024",
        slug: "empresas-tech-mais-desejadas-brasil-2024",
        excerpt: "Pesquisa com 5.000 profissionais de tecnologia aponta as empresas com melhor reputação, cultura e pacote de benefícios. Você vai se surpreender com algumas posições.",
        content: "Todo ano realizamos nossa pesquisa com profissionais de tecnologia brasileiros para mapear as empresas mais desejadas como empregadoras. Os critérios vão além do salário: cultura, propósito, crescimento e bem-estar são fatores decisivos...",
        coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=450&fit=crop",
        category: "Mercado",
        author: "Pedro Alves",
        authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
        readTime: 6,
      },
    ])
    .returning();

  console.log(`Inserted ${articles.length} articles`);
  console.log("Seed complete!");
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
