import { db } from "@workspace/db";
import { companiesTable, jobsTable, articlesTable } from "@workspace/db/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(articlesTable);
  await db.delete(jobsTable);
  await db.delete(companiesTable);

  const companies = await db
    .insert(companiesTable)
    .values([
      {
        name: "Nubank",
        slug: "nubank",
        logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop",
        tagline: "Lutamos contra a complexidade para devolver o controle da vida financeira às pessoas.",
        description: "O Nubank é uma das maiores fintechs do mundo, fundada em 2013 com a missão de combater a complexidade e o abuso do sistema financeiro tradicional. Com mais de 90 milhões de clientes, o Nubank redefine a relação das pessoas com o dinheiro através de produtos simples, transparentes e eficientes. Nossa cultura é orientada por dados e obsessão pelo cliente, com times autônomos e uma mentalidade de startup em escala.",
        category: "fintech",
        size: "grande",
        foundedYear: 2013,
        employeeCount: 8000,
        averageAge: 29,
        city: "São Paulo",
        state: "SP",
        website: "https://nubank.com.br",
        featured: true,
        benefits: ["Plano de saúde premium", "Stock options", "Home office flexível", "Gympass", "Day off no aniversário", "Licença maternidade/paternidade estendida", "Auxílio creche", "Snacks e refeições"],
        values: ["Simplicidade", "Autonomia", "Foco no cliente", "Diversidade e inclusão", "Transparência"],
        photos: [
          "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "iFood",
        slug: "ifood",
        logo: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=400&fit=crop",
        tagline: "Conectando pessoas a comida de qualidade de forma simples e rápida.",
        description: "O iFood é o maior aplicativo de delivery de comida da América Latina. Com presença em mais de 1.000 cidades, conectamos milhões de pessoas a restaurantes e entregadores todos os dias. Nossa missão é deixar as pessoas mais livres para viver melhor. Somos uma empresa orientada por dados, com cultura de inovação e experimentação constante.",
        category: "tech",
        size: "grande",
        foundedYear: 2011,
        employeeCount: 5000,
        averageAge: 31,
        city: "Osasco",
        state: "SP",
        website: "https://ifood.com.br",
        featured: true,
        benefits: ["Plano de saúde", "Vale-refeição", "Home office híbrido", "Gympass", "Bônus por desempenho", "Parcerias com restaurantes", "Curso de idiomas"],
        values: ["Inovação", "Simplicidade", "Impacto", "Colaboração", "Ousadia"],
        photos: [
          "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Conta Simples",
        slug: "conta-simples",
        logo: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1462206092226-f46025ffe607?w=1200&h=400&fit=crop",
        tagline: "A conta empresarial feita para quem não tem tempo a perder.",
        description: "A Conta Simples é uma fintech B2B que oferece conta empresarial, cartão de crédito e gestão de despesas para startups e PMEs. Fundada em 2018, nossa missão é simplificar a vida financeira dos empreendedores brasileiros. Somos uma startup em rápido crescimento, com cultura muito próxima ao cliente e foco em produto.",
        category: "fintech",
        size: "startup",
        foundedYear: 2018,
        employeeCount: 180,
        averageAge: 27,
        city: "São Paulo",
        state: "SP",
        website: "https://contasimples.com",
        featured: true,
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Home office budget", "Cursos e livros", "Day off no aniversário"],
        values: ["Foco no cliente", "Ownership", "Transparência", "Aprendizado contínuo"],
        photos: [
          "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "RD Station",
        slug: "rd-station",
        logo: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=1200&h=400&fit=crop",
        tagline: "Ajudamos empresas a crescer com marketing digital e CRM.",
        description: "A RD Station é a maior plataforma de marketing digital e CRM da América Latina. Fundada em Florianópolis em 2011, hoje atendemos mais de 50.000 empresas no Brasil e no mundo. Nossa cultura é baseada em autonomia, aprendizado e impacto real nos negócios dos nossos clientes. Aqui você vai crescer profissionalmente em um ambiente desafiador e colaborativo.",
        category: "marketing",
        size: "grande",
        foundedYear: 2011,
        employeeCount: 1200,
        averageAge: 30,
        city: "Florianópolis",
        state: "SC",
        website: "https://rdstation.com",
        featured: true,
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Bônus anual", "Cursos pagos", "Participação nos lucros", "Auxílio internet"],
        values: ["Aprendizado", "Resultado", "Diversidade", "Autonomia", "Felicidade"],
        photos: [
          "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Loft",
        slug: "loft",
        logo: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=400&fit=crop",
        tagline: "Reinventando o mercado imobiliário com tecnologia.",
        description: "A Loft é uma proptech que usa tecnologia para simplificar a compra e venda de imóveis residenciais no Brasil. Fundada em 2018 e com aporte de mais de U$700 milhões, somos uma das startups mais valiosas do país. Nosso time combina talentos de tecnologia, produto e negócios para transformar o setor imobiliário.",
        category: "tech",
        size: "media",
        foundedYear: 2018,
        employeeCount: 800,
        averageAge: 30,
        city: "São Paulo",
        state: "SP",
        website: "https://loft.com.br",
        featured: false,
        benefits: ["Plano de saúde", "Stock options", "Home office flexível", "Gympass", "Bônus por metas"],
        values: ["Inovação", "Integridade", "Colaboração", "Impacto"],
        photos: [
          "https://images.unsplash.com/photo-1497366858526-0766cadbe8fa?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Hotmart",
        slug: "hotmart",
        logo: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=1200&h=400&fit=crop",
        tagline: "A plataforma para quem cria, vende e distribui produtos digitais.",
        description: "A Hotmart é a maior plataforma de produtos digitais da América Latina. Conectamos criadores de conteúdo a milhões de compradores em mais de 190 países. Fundada em BH em 2011, hoje somos um unicórnio e seguimos crescendo com a missão de democratizar o empreendedorismo digital.",
        category: "tech",
        size: "grande",
        foundedYear: 2011,
        employeeCount: 1800,
        averageAge: 28,
        city: "Belo Horizonte",
        state: "MG",
        website: "https://hotmart.com",
        featured: true,
        benefits: ["Plano de saúde premium", "Stock options", "Home office total", "Cursos ilimitados", "Day off no aniversário", "Gympass"],
        values: ["Liberdade", "Crescimento", "Impacto", "Diversidade", "Inovação"],
        photos: [
          "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&h=500&fit=crop",
          "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Pipefy",
        slug: "pipefy",
        logo: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=400&fit=crop",
        tagline: "Automatize processos e ganhe eficiência com nossa plataforma no-code.",
        description: "O Pipefy é uma plataforma de gestão de processos e automação sem código. Atendemos empresas em mais de 150 países e estamos mudando a forma como as organizações trabalham. Nossa cultura é international-first, com times distribuídos pelo Brasil e pelo mundo, e forte compromisso com a excelência no produto.",
        category: "tech",
        size: "media",
        foundedYear: 2015,
        employeeCount: 600,
        averageAge: 29,
        city: "Curitiba",
        state: "PR",
        website: "https://pipefy.com",
        featured: false,
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Inglês custeado", "Home office budget", "Gympass"],
        values: ["Excelência", "Ownership", "Aprendizado", "Colaboração"],
        photos: [
          "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=500&fit=crop",
        ],
      },
      {
        name: "Sympla",
        slug: "sympla",
        logo: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=200&h=200&fit=crop",
        coverImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&h=400&fit=crop",
        tagline: "A plataforma de eventos mais usada do Brasil.",
        description: "A Sympla é a maior plataforma de venda de ingressos e gestão de eventos do Brasil. Atendemos mais de 200.000 eventos por ano, desde shows a cursos online. Somos parte do grupo Locaweb e seguimos crescendo como startup dentro de um grupo de tecnologia consolidado.",
        category: "tech",
        size: "media",
        foundedYear: 2012,
        employeeCount: 350,
        averageAge: 30,
        city: "Belo Horizonte",
        state: "MG",
        website: "https://sympla.com.br",
        featured: false,
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Cursos pagos", "Participação nos lucros"],
        values: ["Inovação", "Simplicidade", "Foco no cliente", "Agilidade"],
        photos: [
          "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
        ],
      },
    ])
    .returning();

  console.log(`Inserted ${companies.length} companies`);

  const jobs = await db
    .insert(jobsTable)
    .values([
      {
        title: "Senior Software Engineer - Backend",
        slug: "senior-software-engineer-backend-nubank",
        companyId: companies[0].id,
        category: "tech",
        description: "Buscamos um(a) engenheiro(a) de software sênior para trabalhar com nosso time de plataforma, desenvolvendo sistemas distribuídos de alta escala que processam milhões de transações diárias. Você vai trabalhar com Clojure, Kotlin, AWS e Kafka em um ambiente de alta performance e autonomia.",
        requirements: ["5+ anos de experiência com desenvolvimento backend", "Experiência com sistemas distribuídos", "Conhecimento em Clojure ou Kotlin (diferencial)", "Experiência com AWS", "Inglês intermediário"],
        benefits: ["Plano de saúde premium", "Stock options", "Home office flexível", "Gympass"],
        city: "São Paulo",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 18000,
        salaryMax: 28000,
        featured: true,
      },
      {
        title: "Product Manager - Growth",
        slug: "product-manager-growth-nubank",
        companyId: companies[0].id,
        category: "produto",
        description: "Como PM de Growth no Nubank, você será responsável por identificar e explorar oportunidades para aumentar a aquisição, ativação e retenção de clientes. Trabalhará de forma cross-funcional com engenharia, design e data science para lançar features que impactem milhões de usuários.",
        requirements: ["4+ anos de experiência em product management", "Experiência com growth hacking e métricas de produto", "Capacidade analítica forte", "Experiência com testes A/B", "Inglês fluente"],
        benefits: ["Plano de saúde premium", "Stock options", "Home office flexível"],
        city: "São Paulo",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 20000,
        salaryMax: 30000,
        featured: true,
      },
      {
        title: "Data Analyst - Marketing",
        slug: "data-analyst-marketing-ifood",
        companyId: companies[1].id,
        category: "dados",
        description: "Você vai trabalhar no time de analytics de marketing do iFood, ajudando a entender o comportamento dos usuários e otimizar campanhas. Usamos SQL, Python e ferramentas de BI para gerar insights que impactam diretamente a estratégia da empresa.",
        requirements: ["2+ anos de experiência em análise de dados", "SQL avançado", "Experiência com Python (pandas, numpy)", "Conhecimento em ferramentas de BI (Tableau, Looker)", "Raciocínio analítico"],
        benefits: ["Plano de saúde", "Vale-refeição", "Home office híbrido", "Gympass"],
        city: "Osasco",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 8000,
        salaryMax: 13000,
        featured: false,
      },
      {
        title: "UX Designer - Mobile",
        slug: "ux-designer-mobile-ifood",
        companyId: companies[1].id,
        category: "design",
        description: "Buscamos um(a) UX Designer para trabalhar no aplicativo de consumidores do iFood. Você vai fazer pesquisa com usuários, criar wireframes e protótipos, e colaborar de perto com engenharia e produto para criar experiências excepcionais para nossos 50 milhões de usuários.",
        requirements: ["3+ anos de experiência em UX design", "Portfólio com projetos de mobile", "Experiência com Figma", "Conhecimento em design research", "Capacidade de comunicação clara"],
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Cursos pagos"],
        city: "Osasco",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "pleno",
        salaryMin: 9000,
        salaryMax: 14000,
        featured: false,
      },
      {
        title: "Full Stack Engineer",
        slug: "full-stack-engineer-conta-simples",
        companyId: companies[2].id,
        category: "tech",
        description: "Na Conta Simples você vai trabalhar como engenheiro(a) full stack construindo a infraestrutura financeira para PMEs brasileiras. Nossa stack é React, Node.js e PostgreSQL. Somos um time pequeno e autônomo, onde cada pessoa tem grande impacto.",
        requirements: ["2+ anos de experiência full stack", "React e TypeScript", "Node.js", "PostgreSQL", "Experiência com APIs REST"],
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Home office budget"],
        city: "São Paulo",
        state: "SP",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 10000,
        salaryMax: 16000,
        featured: true,
      },
      {
        title: "Marketing Manager - Inbound",
        slug: "marketing-manager-inbound-rdstation",
        companyId: companies[3].id,
        category: "marketing",
        description: "A RD Station busca um(a) Marketing Manager para liderar a estratégia de inbound marketing. Você vai gerenciar a produção de conteúdo, SEO e estratégias de geração de leads para nosso ICP de PMEs. Experiência com a própria plataforma RD Station é um grande diferencial.",
        requirements: ["4+ anos de experiência em marketing digital", "Experiência com inbound marketing e SEO", "Capacidade analítica para interpretar métricas", "Experiência com CRM", "Liderança de times"],
        benefits: ["Plano de saúde", "Home office híbrido", "Gympass", "Bônus anual"],
        city: "Florianópolis",
        state: "SC",
        modality: "hibrido",
        contractType: "clt",
        level: "senior",
        salaryMin: 11000,
        salaryMax: 17000,
        featured: false,
      },
      {
        title: "Estágio em Produto Digital",
        slug: "estagio-produto-digital-hotmart",
        companyId: companies[5].id,
        category: "produto",
        description: "Junte-se ao time de produto da Hotmart como estagiário(a) e aprenda na prática como construir produtos digitais usados por milhões de pessoas. Você vai trabalhar junto com PMs e designers em pesquisas, análises e discovery de produto.",
        requirements: ["Cursando últimos semestres de curso superior em Administração, Engenharia ou áreas relacionadas", "Interesse em tecnologia e produtos digitais", "Boa comunicação", "Inglês intermediário"],
        benefits: ["Bolsa auxílio compatível", "Plano de saúde", "Cursos ilimitados", "Day off no aniversário"],
        city: "Belo Horizonte",
        state: "MG",
        modality: "hibrido",
        contractType: "estagio",
        level: "junior",
        salaryMin: 2000,
        salaryMax: 3000,
        featured: false,
      },
      {
        title: "Frontend Engineer - React",
        slug: "frontend-engineer-react-pipefy",
        companyId: companies[6].id,
        category: "tech",
        description: "Buscamos um(a) Frontend Engineer para trabalhar na interface do Pipefy, usada por empresas ao redor do mundo. Nossa stack é React, TypeScript e GraphQL. Você vai construir features complexas de uma plataforma no-code de gestão de processos.",
        requirements: ["3+ anos de experiência com React", "TypeScript", "GraphQL", "Testes automatizados", "Inglês para comunicação com time internacional"],
        benefits: ["Plano de saúde", "Stock options", "100% remoto", "Inglês custeado", "Home office budget"],
        city: "Curitiba",
        state: "PR",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 10000,
        salaryMax: 16000,
        featured: false,
      },
      {
        title: "Tech Lead - Plataforma",
        slug: "tech-lead-plataforma-nubank",
        companyId: companies[0].id,
        category: "tech",
        description: "Estamos buscando um(a) Tech Lead para o time de plataforma do Nubank. Você vai liderar tecnicamente um time de engenheiros, definir a arquitetura de sistemas de alta escala e garantir a qualidade do código e das entregas. Experiência com liderança técnica e sistemas distribuídos é essencial.",
        requirements: ["7+ anos de experiência em engenharia de software", "Experiência com liderança técnica de times", "Sistemas distribuídos e cloud", "Clojure, Kotlin ou linguagens funcionais (diferencial)", "Inglês fluente"],
        benefits: ["Plano de saúde premium", "Stock options agressivos", "Bônus por performance", "Home office flexível"],
        city: "São Paulo",
        state: "SP",
        modality: "hibrido",
        contractType: "clt",
        level: "especialista",
        salaryMin: 28000,
        salaryMax: 42000,
        featured: true,
      },
      {
        title: "Social Media Analyst",
        slug: "social-media-analyst-hotmart",
        companyId: companies[5].id,
        category: "marketing",
        description: "A Hotmart busca um(a) Social Media Analyst criativo(a) para gerenciar nossa presença nas redes sociais no Brasil e América Latina. Você vai criar conteúdo, gerir campanhas e analisar métricas de engajamento para uma marca que inspira empreendedores.",
        requirements: ["2+ anos de experiência em social media", "Criatividade e produção de conteúdo", "Conhecimento em métricas de redes sociais", "Experiência com ferramentas de gestão (Sprout, Buffer)", "Espanhol é diferencial"],
        benefits: ["Plano de saúde premium", "Stock options", "Home office total", "Cursos ilimitados"],
        city: "Belo Horizonte",
        state: "MG",
        modality: "remoto",
        contractType: "clt",
        level: "pleno",
        salaryMin: 5000,
        salaryMax: 8000,
        featured: false,
      },
    ])
    .returning();

  console.log(`Inserted ${jobs.length} jobs`);

  const articles = await db
    .insert(articlesTable)
    .values([
      {
        title: "Como se destacar em processos seletivos de startups em 2024",
        slug: "como-se-destacar-processos-seletivos-startups",
        excerpt: "Startups contratam diferente. Entenda o que os recrutadores de tech realmente buscam e como preparar sua candidatura para se diferenciar.",
        content: "O mercado de trabalho em startups tem características próprias. Diferente de grandes corporações, as startups buscam pessoas com alta autonomia, capacidade de aprender rápido e tolerância à ambiguidade...",
        coverImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=450&fit=crop",
        category: "Carreira",
        author: "Ana Paula Mendes",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
        readTime: 7,
      },
      {
        title: "Salários em tech no Brasil: o que esperar em 2024",
        slug: "salarios-tech-brasil-2024",
        excerpt: "Pesquisa exclusiva com mais de 2.000 profissionais de tecnologia revela as faixas salariais por cargo, nível e stack. Veja como você se posiciona.",
        content: "O mercado de tecnologia no Brasil segue aquecido, mesmo com os movimentos de layoffs globais de 2023. Analisamos dados de mais de 2.000 profissionais para trazer um panorama real das remunerações...",
        coverImage: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=450&fit=crop",
        category: "Mercado",
        author: "Carlos Eduardo Silva",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
        readTime: 10,
      },
      {
        title: "Remote work no Brasil: o guia completo para trabalhar de qualquer lugar",
        slug: "remote-work-brasil-guia-completo",
        excerpt: "Do regime CLT ao PJ, dos impostos à produtividade: tudo que você precisa saber para trabalhar remotamente no Brasil com segurança jurídica e financeira.",
        content: "Trabalho remoto virou realidade para milhões de brasileiros. Mas além da flexibilidade, existem questões práticas importantes: qual regime contratar? Como organizar sua rotina? Como pagar impostos corretamente?...",
        coverImage: "https://images.unsplash.com/photo-1585974738771-84483dd9f89f?w=800&h=450&fit=crop",
        category: "Carreira",
        author: "Mariana Costa",
        authorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop",
        readTime: 12,
      },
      {
        title: "Employer branding: por que as melhores startups disputam talentos com cultura",
        slug: "employer-branding-startups-cultura",
        excerpt: "Nubank, iFood, Hotmart. O que essas empresas têm em comum além do tamanho? Uma cultura de empresa que atrai e retém os melhores profissionais. Veja como elas fazem isso.",
        content: "Nos últimos anos, o employer branding deixou de ser uma iniciativa de RH para se tornar vantagem competitiva estratégica. As startups que mais crescem no Brasil entenderam que a guerra pelo talento se vence antes mesmo da vaga abrir...",
        coverImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=450&fit=crop",
        category: "Empresas",
        author: "Felipe Rodrigues",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
        readTime: 8,
      },
      {
        title: "Da faculdade para a startup: guia para quem quer entrar no mercado de tech",
        slug: "faculdade-startup-guia-iniciantes-tech",
        excerpt: "Recém-formado ou ainda na faculdade? Veja como estruturar seu portfólio, escolher os primeiros projetos e conseguir seu primeiro emprego em uma startup de tecnologia.",
        content: "Entrar no mercado de tech pode parecer intimidador. Você olha para as vagas e parece que todo mundo precisa de 5 anos de experiência para uma posição júnior. Mas existem caminhos para quem está começando...",
        coverImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&h=450&fit=crop",
        category: "Carreira",
        author: "Lucas Almeida",
        authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
        readTime: 9,
      },
      {
        title: "CLT vs PJ: qual é melhor para quem trabalha em tech?",
        slug: "clt-vs-pj-tech-brasil",
        excerpt: "A dúvida que todo profissional de tech enfrenta: CLT ou PJ? Fizemos os cálculos para diferentes cenários e mostramos quando cada regime compensa.",
        content: "Com o avanço do trabalho remoto e das fintechs, cada vez mais profissionais de tecnologia são contratados como PJ. Mas será que isso sempre compensa? Fizemos uma análise detalhada considerando impostos, benefícios e estabilidade...",
        coverImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=450&fit=crop",
        category: "Mercado",
        author: "Juliana Ferreira",
        authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
        readTime: 11,
      },
    ])
    .returning();

  console.log(`Inserted ${articles.length} articles`);
  console.log("Seed complete!");
}

seed().catch(console.error);
